### ISSUE TITLE
The jar-file is recognised as dangerous by Windows-Defender

### ISSUE THREAD

**Issue by erardlucien** [VitasSalvantes/Web-Krypto#4]
I try another way to use it but i only have failure.

**Comment by VitasSalvantes** [comment]
Hi,

thanks for your feedback!  Judging by the logs that you sent me, I can assume the following: you did not allow the firewall to give access to this application.

For the application to work successfully, you must allow access to the network. Try [this](https://windowscrazy.com/979-how-to-allow-java-through-firewall-windows-10/) and please give me feedback.

Regards
[VitasSalvantes](https://github.com/VitasSalvantes/)

**Comment by erardlucien** [comment]
Everything is working. I have to stop Postgresql-sever first.
